name: Set Commit Time

on:
  workflow_run:
    workflows: ["Lighthouse CI"]
    types:
      - completed

jobs:
  set-commit-time:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Commit Time
        run: |
          current_date=$(date +'%m-%d-%Y %H:%M:%S')
          sed -i "s/<p id=\"date\">.*<\/p>/<p id=\"date\">Test Results Date: $current_date<\/p>/" index.html

          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add index.html  
          git commit -m "Update last commit date [skip ci]"
          git push -f
        continue-on-error: true
