name: Update Know your Meme Title

on:
  workflow_run:
    workflows: ["Lighthouse CI"]
    types:
      - completed

jobs:
  update-files-kym:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Update kym.html File
        run: |
          sed -i "" "s/<h1 id=\"title\">.*<\/h1>/<h1 id=\"title\">Know your Meme Results<\/h1>/" pytest/kym.html

          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add pytest/kym.html
          git commit -m "Update Know your Meme Results [skip ci]"
          git push -f
        continue-on-error: true
