name: Update Cheezburger Title

on:
  workflow_run:
    workflows: ["Lighthouse CI"]
    types:
      - completed

jobs:
  update-files-chz:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Update chz.html File
        run: |
          sed -i "" 's/<h1 id="title">.*<\/h1>/<h1 id="title">Cheezburger Results<\/h1>/' pytest/chz.html

          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add pytest/chz.html
          git commit -m "Update Cheezburger Results [skip ci]"
          git push -f
        continue-on-error: true
