name: Update Files and Set Commit Time

on:
  workflow_run:
    workflows: ["Lighthouse CI"]
    types:
      - completed

jobs:
  set-commit-time:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Commit Time
        run: |
          current_content=$(cat pytest/index.html)  
          current_date=$(date +'%m-%d-%Y %H:%M:%S')
          new_content="<div class=\"centered-text\">\n    <h1>ðŸ¤– QA Automation</h1>\n</div>\n<p id=\"date\">Test Results Date: $current_date</p>"
          updated_content="${current_content/<div class=\"centered-text\">\n    <h1>ðŸ¤– QA Automation<\/h1>\n<\/div>/$new_content}"
          echo -e "$updated_content" > pytest/index.html  
          
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add pytest/index.html  
          git commit -m "Update last commit date [skip ci]"
          git push -f
        continue-on-error: true

  update-files-chz:
    runs-on: ubuntu-latest
    needs: set-commit-time

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Update chz.html File
        run: |
          file="pytest/chz.html"
          sed -i "s/<p id=\"title\">.*<\/p>/<p id=\"title\">Cheezburger Results<\/p>/" $file

          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add $file
          git commit -m "Update Cheezburger Results [skip ci]"
          git push -f
        continue-on-error: true

  update-files-crd:
    runs-on: ubuntu-latest
    needs: set-commit-time

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Update crd.html File
        run: |
          file="pytest/crd.html"
          sed -i "s/<p id=\"title\">.*<\/p>/<p id=\"title\">Cracked Results<\/p>/" $file

          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add $file
          git commit -m "Update Cracked Results [skip ci]"
          git push -f
        continue-on-error: true

  update-files-ebw:
    runs-on: ubuntu-latest
    needs: set-commit-time

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Update ebw.html File
        run: |
          file="pytest/ebw.html"
          sed -i "s/<p id=\"title\">.*<\/p>/<p id=\"title\">Ebaum's World Results<\/p>/" $file

          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add $file
          git commit -m "Update Ebaum's World Results [skip ci]"
          git push -f
        continue-on-error: true

  update-files-kym:
    runs-on: ubuntu-latest
    needs: set-commit-time

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Update kym.html File
        run: |
          file="pytest/kym.html"
          sed -i "s/<p id=\"title\">.*<\/p>/<p id=\"title\">Know your Meme Results<\/p>/" $file

          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add $file
          git commit -m "Update Know your Meme Results [skip ci]"
          git push -f
        continue-on-error: true

